name: "Build"

on:
  push:
  pull_request:

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v9
        with:
          nix-installer-tag: v0.15.1
      - uses: DeterminateSystems/magic-nix-cache-action@v3
      - run: nix --print-build-logs build .
